### ISSUE TITLE
Packaging for kali

### ISSUE THREAD

**Issue by Jubei-Mitsuyoshi** [brav0hax/easy-creds#14]
hi am packaging this for debian/kali the file definitions.sslstrip, where does it go? and whats it for? it does not seem to be referenced in the installer.
Also the script seems to need svn/git versions of a lot of packages, before i go of and start packaging all its cutting edge deps, has it been tested on a standard kali setup, if so where does it fall over, a lot of kali packages are seriously out of date, is that going to effect operation ?

**Comment by ZeroChaos-** [comment]
Maybe it would be easier to use a distro which isn't seriously out of date then...  We can try and support you but seriously man, how about trying a little and coming to us with an actual problem rather than rambling about wether you can do it or not?

**Comment by cmavr8** [comment]
Lol. True, start a VM of Kali and try it.
I'm using EC on Kali btw, but can't remember if I had to install extra stuff. One sure thing is that you need to edit various files etc to enable features. Most of them are described in the Prerequisites menu of EC.

On Jubei's defence, Kali is a very popula sec distro, and it would be neat to have EC integrated.

**Comment by Jubei-Mitsuyoshi** [comment]
Yea i know i know, pick something with arch in it :)
Yep looked at the pre-requs all seems cool and clear, if your running a very custom setup then great, but in packaging i have to make sure it lives happily beside all sorts of other crap.
The simple answer is just create updated packages to fulfill the pre-reqs, completely ( not just in label ) which will do.
Kali has its faults (LOTS), but its the only pentest distro running nice on arm, that kind of makes it the future :)
I have about 20-30 packages on the go, dont have time to test everything in depth, so once all finished would it be ok to ask one of you guys to test the packages ? You could tell if something was fucked in mins, take me days.

**Comment by cmavr8** [comment]
Ok, I guess I can do a little testing on a clean VM :)

**Comment by Jubei-Mitsuyoshi** [comment]
Coo be done in 2 days, will stick it in the repo  https://github.com/Jubei-Mitsuyoshi/aaa-debian-repo.git
along with the git/svn versions of the kali deps, that way you can pull the whole lot in one go, the instructions for repo are in readme.
Thanks loads :)

**Comment by Jubei-Mitsuyoshi** [comment]
Ok its in the repo for testing, its a local download

cd some/dir

apt-get install git

git clone https://github.com/Jubei-Mitsuyoshi/aaa-debian-repo.git

echo "deb [trusted=yes] file:///path/to/some/dir public distro/distrogit" (ie kali,kaligit or unstable,unstablegit or all of them) >> /etc/apt/sources.list

apt-get update

easycreds is in the kali section, seems kali has had a BIG shake up, all the deps should be up to required versions from standard kali repos.

If you want to add anything to description or deb information give me a shout

**Comment by cmavr8** [comment]
I'll try to test it tonight or in the weekend, will report back.

**Comment by cmavr8** [comment]
Hi, here's my initial report:
Installed  EC per your instructions on a fresh kali 1.0 VM. First time I ran it I got:
"# easy-creds 
[!] Couldn't find radiusd. If its installed please create a symbolic link in /usr/bin
[!] Some prereqs missing, functionality may be impaired. Review README file."

Then I get the menu. Going into prerequisites, and choosing "3.  Install karmetasploit prereqs" I get:
"[*] Installing Karmetasploit Prerequisites, please standby.

Building native extensions.  This could take a while...
ERROR:  Error installing activerecord:
    ERROR: Failed to build gem native extension.

```
    /usr/bin/ruby1.9.1 extconf.rb
```

/usr/lib/ruby/1.9.1/rubygems/custom_require.rb:36:in `require': cannot load such file -- mkmf (LoadError)
    from /usr/lib/ruby/1.9.1/rubygems/custom_require.rb:36:in`require'
    from extconf.rb:13:in '< main >'

Gem files will remain installed in /var/lib/gems/1.9.1/gems/atomic-1.1.14 for inspection.
Results logged to /var/lib/gems/1.9.1/gems/atomic-1.1.14/ext/gem_make.out

[+] Finished installing Karmetasploit Prerequisites."

I can't troubleshoot it right now, sorry. 

BUT: I tried the main Fake AP attacks (menu #3, attacks 1-3) and they work fine! I guess the others (menu #2) are simpler so will also work.
